name: Build-Curl

on:
  push:
    branches:
      - main

permissions: 
  contents: read
  id-token: write

jobs:
  build-and-curl:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: docker-build
        run: |
          docker build -t pipeline-test .

      - name: docker-run
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_PROD }} 
        run: |
          docker run -d -p 8000:8000 -e DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" pipeline-test

      - name: curl-ftw
        run: |
          sleep 10
          curl -f http://localhost:8000/

  sbom-scan-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Trufflehog Secrets Scan
        uses: trufflesecurity/trufflehog@main 
        with:
          path: ./
          base: ""
          head: "HEAD"
          extra_args: --only-verified

      - name: sbom_gen_and_scan
        uses: ./.github/actions/sbom-scan

      - name: upload_sbom
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: project-sbom
          path: sbom.json
          compression-level: 0

  terraform-stage-1:
    needs: [build-and-curl, sbom-scan-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Authenticate to AWS via Keys
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: terraform-stage-1
        uses: ./.github/actions/terraform
        with:
          STATE_KEY: ${{ secrets.STATE_KEY }}
          TF_STAGE: 'stage1'

  build-tag-push:
    needs: terraform-stage-1
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Authenticate to AWS via Keys
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: docker_build_tag_push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t application-final .
          docker tag application-final $ECR_REGISTRY/django_image:latest
          docker push $ECR_REGISTRY/django_image:latest
          

  terraform-stage-2:
    needs: build-tag-push
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Authenticate to AWS via Keys
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: terraform-stage-2
        uses: ./.github/actions/terraform
        with:
          STATE_KEY: ${{ secrets.STATE_KEY }}
          TF_STAGE: 'stage2' 
          DJANGO_SECRET_KEY_PROD: ${{ secrets.DJANGO_SECRET_KEY_PROD }}

  pre-eval:
    needs: terraform-stage-2
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Authenticate to AWS via Keys
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get_container_dns
        run: |
          echo "Allowing serverless container tasks to provision public network adapters..."
          sleep 60
          
          TASK_ARN=$(aws ecs list-tasks --cluster django-production-cluster --service-name django-fargate-service --query "taskArns" --output text)
          
          ENI_ID=$(aws ecs describe-tasks --cluster django-production-cluster --tasks "$TASK_ARN" --query "tasks.attachments.details[?name=='networkInterfaceId'].value" --output text)
          
          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids "$ENI_ID" --query "NetworkInterfaces.Association.PublicIp" --output text)
          
          echo "Target live container public IP address discovered: http://$PUBLIC_IP:8000"
          echo "=== Executing Rubric-Mandated HTTP Health Check ==="
          curl -f "http://$PUBLIC_IP:8000/"
