name: Build-Curl-AWS

on:
  push:
    branches:
      - main

permissions: 
  contents: read
  id-token: write

jobs:
  build-and-curl:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: docker-build
        run: |
          docker build -t pipeline-test .

      - name: docker-run
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          docker run -d -p 8000:8000 -e DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" pipeline-test

      - name: curl-ftw
        run: |
          sleep 10
          curl -f http://localhost:8000/
